### PR TITLE
PLF-8034 Fix NodeHierarchyCreator startup

### PR DESCRIPTION
**Pull request by boubaker**
The permission changes should be made on user private nodes only and not for generic nodes that are created on server startup.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
@boubaker Looks good, but can we cover this case by an unit test ?

**Comment by thomasdelhomenie** [comment]
Why ? It would avoid to have regressions in the future for this case.

**Comment by thomasdelhomenie** [comment]
I just want to be sure that the issue we had in PLF-8034 cannot happen again in the future when we will do changes in this class.

**Comment by boubaker** [comment]
Yep, I'm ok with that, but which Test Case to implement in you opinion ?

**Comment by thomasdelhomenie** [comment]
Cannot we add a test which checks the state of the created nodes to make sure the permissions are not updated in this case for example ?

**Comment by boubaker** [comment]
The permissions aren't updated even before the PR, because the userName is null, but it triggers a permission change event so that ES attempt to reindex the whole hierarchy while there is no real change.

**Comment by thomasdelhomenie** [comment]
OK so the test on permissions change would not help here indeed, but we could check if the permission change event is not triggered in this case, right ?

**Comment by boubaker** [comment]
Not even, because it will be triggered when creating the document.

In addition, a test that a listener is not triggered, and an extra event is not added etc is worthless, else we will have to test if nothing else was done except what we know that was done. That's why, a  PR for performance improvements doesn't need in general case a Test case because no change on the result is made.

**Comment by thomasdelhomenie** [comment]
Having a test to make sure we will not fall in the same issue that we faced is always worthwhile IMO, being it a performance test or not, but I understand it is not that simple to add a test for this case so let's move on.

**Comment by boubaker** [comment]
> not that simple

if you see it so, I 'll not try to convince you with a different idea

**Pull request merged**
