### PR TITLE
JCR-2453 : make JCR quota test more determinist

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
This PR sets the quotas sizes  relative to the current data size to be sure quotas are always correct.

### CODE REVIEW

**Comment by aboughzela** [comment]
Why this problem is random ?
it's seem the quota is not updated after removed data

**Comment by thomasdelhomenie** [comment]
I added some trace to try to understand and noticed that sometimes the size of the data is bigger than expected. So it is maybe due to a cleanup data, but I did not figure out where it can happen.
Making the quota relative to the data size make them more deterministic, but there is maybe another underlying issue I agree.

**Comment by aboughzela** [comment]
I have fixed the same problem by  added a sleep(timeout), to make sure the changes are persisted 
can see on https://jira.exoplatform.org/browse/JCR-2290 
PR https://github.com/exodev/jcr/commit/268df3890cbd96c14bb9847ef8aa2b516c648e34

**Comment by thomasdelhomenie** [comment]
I am not sure it is the same root cause. But using relative quotas feels like more deterministic to me than using Thread.sleep. With relative quotas we are sure to set the quotas higher or lower than the current value.
If it is really due to PushTask thread, is there a way to force to execute it before running the test ?

**Comment by aboughzela** [comment]
PushTask thread is executed Periodically , add  sleeep 5000 to be sure to get the real workspace/repository size.
As you don't have the real cause of this random error , We can use  relative quotas  as workarround
The real cause should be resolved (As you know Quota service is not integrated as supported feature)
WDYT ?

**Comment by thomasdelhomenie** [comment]
Using sleep is not a good practice to me. We need a way to enforce the PushTask thread is executed, a method to call it from the test.
But I agree, let's validate this first fix (relative quotas) and work on a better solution on a dedicated issue.

**Comment by aboughzela** [comment]
LGTM

**Pull request merged**
